# Generated by Django 6.0.6 on 2026-07-13 18:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Example: QA, ENG, PROC, CERT', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Document categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerVDRLTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_code', models.CharField(help_text='Example: PETROFAC-STD or ADNOC-BALL-VALVE', max_length=50)),
                ('template_name', models.CharField(max_length=200)),
                ('revision', models.CharField(default='0', help_text='Template revision, for example 0, 1, A or B.', max_length=20)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use this as the default template for the selected customer.')),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vdrl_templates', to='core.customer')),
            ],
            options={
                'ordering': ['customer__name', 'template_name', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='DocumentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_document_code', models.CharField(help_text='Internal document code, for example ITP or QAP.', max_length=50, unique=True)),
                ('document_title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.documentcategory')),
                ('default_responsible_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_documents', to='core.department')),
            ],
            options={
                'ordering': ['category__name', 'document_title'],
            },
        ),
        migrations.CreateModel(
            name='CustomerVDRLTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveSmallIntegerField(help_text='Document sequence number in the VDRL.')),
                ('customer_document_code', models.CharField(blank=True, help_text='Customer-assigned document code, if applicable.', max_length=100)),
                ('customer_document_title', models.CharField(blank=True, help_text='Customer-specific title. Leave blank to use the internal document title.', max_length=250)),
                ('requirement_type', models.CharField(choices=[('MANDATORY', 'Mandatory'), ('OPTIONAL', 'Optional'), ('CONDITIONAL', 'Conditional')], default='MANDATORY', max_length=20)),
                ('condition_description', models.TextField(blank=True, help_text='Required when Requirement Type is Conditional. Example: Applicable only for cryogenic valves.')),
                ('submission_stage', models.CharField(choices=[('AFTER_ORDER', 'After Order Receipt'), ('AFTER_KICKOFF', 'After Kick-off Meeting'), ('BEFORE_PROCUREMENT', 'Before Procurement'), ('BEFORE_MANUFACTURING', 'Before Manufacturing'), ('BEFORE_INSPECTION', 'Before Inspection'), ('BEFORE_DELIVERY', 'Before Delivery'), ('FINAL_DOSSIER', 'Final Dossier / MRB'), ('AS_REQUIRED', 'As Required'), ('MANUAL', 'Manually Planned')], default='AFTER_ORDER', max_length=30)),
                ('due_date_basis', models.CharField(choices=[('ORDER_DATE', 'Sales Order Date'), ('KICKOFF_DATE', 'Kick-off Meeting Date'), ('PROCUREMENT_DATE', 'Planned Procurement Date'), ('MANUFACTURING_DATE', 'Manufacturing Start Date'), ('INSPECTION_DATE', 'Planned Inspection Date'), ('DELIVERY_DATE', 'Planned Delivery Date'), ('MANUAL', 'Manual Date')], default='ORDER_DATE', max_length=30)),
                ('day_offset', models.IntegerField(default=0, help_text='Positive number means days after the basis date. Negative number means days before the basis date.')),
                ('customer_review_days', models.PositiveIntegerField(blank=True, help_text="Leave blank to use the customer's standard review period.", null=True)),
                ('approval_required', models.BooleanField(default=True)),
                ('crs_required', models.BooleanField(default=True)),
                ('include_in_final_mrb', models.BooleanField(default=True)),
                ('required_file_format', models.CharField(choices=[('PDF', 'PDF'), ('NATIVE', 'Native / Editable File'), ('PDF_AND_NATIVE', 'PDF and Native File'), ('OTHER', 'Other')], default='PDF', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('responsible_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_vdrl_template_items', to='core.department')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.customervdrltemplate')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_template_items', to='core.documentmaster')),
            ],
            options={
                'ordering': ['template', 'sequence_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='customervdrltemplate',
            constraint=models.UniqueConstraint(fields=('customer', 'template_code', 'revision'), name='unique_customer_template_revision'),
        ),
        migrations.AddConstraint(
            model_name='customervdrltemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'sequence_number'), name='unique_sequence_per_customer_vdrl_template'),
        ),
    ]
