# Generated by Django 6.0.6 on 2026-07-14 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_documentcategory_customervdrltemplate_documentmaster_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='kickoff_date',
            field=models.DateField(blank=True, help_text='Project kick-off meeting date.', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='manufacturing_start_date',
            field=models.DateField(blank=True, help_text='Planned manufacturing start date.', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='planned_inspection_date',
            field=models.DateField(blank=True, help_text='Planned first inspection date.', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='planned_procurement_date',
            field=models.DateField(blank=True, help_text='Planned procurement start date.', null=True),
        ),
        migrations.CreateModel(
            name='SalesOrderVDRL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vdrl_number', models.CharField(help_text='Example: MTV2607001-VDRL-001', max_length=100)),
                ('title', models.CharField(default='Vendor Document Requirement List', max_length=250)),
                ('revision', models.CharField(default='0', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('is_current', models.BooleanField(default=True, help_text='Indicates the current working VDRL revision.')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_sales_order_vdrls', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vdrls', to='core.salesorder')),
                ('source_template', models.ForeignKey(blank=True, help_text='Customer template used to generate this Sales Order VDRL.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_vdrls', to='core.customervdrltemplate')),
            ],
            options={
                'ordering': ['-created_at', 'sales_order__sales_order_number'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderVDRLDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveSmallIntegerField()),
                ('customer_document_code', models.CharField(blank=True, max_length=100)),
                ('document_title', models.CharField(max_length=250)),
                ('requirement_type', models.CharField(choices=[('MANDATORY', 'Mandatory'), ('OPTIONAL', 'Optional'), ('CONDITIONAL', 'Conditional')], default='MANDATORY', max_length=20)),
                ('condition_description', models.TextField(blank=True)),
                ('applicability_status', models.CharField(choices=[('REQUIRED', 'Required'), ('TO_CONFIRM', 'To Be Confirmed'), ('NOT_APPLICABLE', 'Not Applicable')], default='REQUIRED', max_length=20)),
                ('submission_stage', models.CharField(choices=[('AFTER_ORDER', 'After Order Receipt'), ('AFTER_KICKOFF', 'After Kick-off Meeting'), ('BEFORE_PROCUREMENT', 'Before Procurement'), ('BEFORE_MANUFACTURING', 'Before Manufacturing'), ('BEFORE_INSPECTION', 'Before Inspection'), ('BEFORE_DELIVERY', 'Before Delivery'), ('FINAL_DOSSIER', 'Final Dossier / MRB'), ('AS_REQUIRED', 'As Required'), ('MANUAL', 'Manually Planned')], default='AFTER_ORDER', max_length=30)),
                ('due_date_basis', models.CharField(choices=[('ORDER_DATE', 'Sales Order Date'), ('KICKOFF_DATE', 'Kick-off Meeting Date'), ('PROCUREMENT_DATE', 'Planned Procurement Date'), ('MANUFACTURING_DATE', 'Manufacturing Start Date'), ('INSPECTION_DATE', 'Planned Inspection Date'), ('DELIVERY_DATE', 'Planned Delivery Date'), ('MANUAL', 'Manual Date')], default='ORDER_DATE', max_length=30)),
                ('day_offset', models.IntegerField(default=0)),
                ('planned_submission_date', models.DateField(blank=True, null=True)),
                ('forecast_submission_date', models.DateField(blank=True, null=True)),
                ('customer_review_days', models.PositiveIntegerField(default=14)),
                ('current_revision', models.CharField(default='0', max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('UNDER_PREPARATION', 'Under Preparation'), ('INTERNAL_REVIEW', 'Internal Review'), ('READY_FOR_SUBMISSION', 'Ready for Submission'), ('SUBMITTED', 'Submitted to Customer'), ('UNDER_CUSTOMER_REVIEW', 'Under Customer Review'), ('RETURNED_WITH_COMMENTS', 'Returned with Comments'), ('COMMENT_ASSESSMENT', 'Comment Assessment in Progress'), ('REVISION_IN_PROGRESS', 'Revision in Progress'), ('CRS_IN_PROGRESS', 'CRS Preparation in Progress'), ('READY_FOR_RESUBMISSION', 'Ready for Resubmission'), ('RESUBMITTED', 'Resubmitted to Customer'), ('APPROVED_WITH_COMMENTS', 'Approved with Comments'), ('APPROVED', 'Approved'), ('ON_HOLD', 'On Hold'), ('NOT_APPLICABLE', 'Not Applicable'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=40)),
                ('approval_required', models.BooleanField(default=True)),
                ('crs_required', models.BooleanField(default=True)),
                ('include_in_final_mrb', models.BooleanField(default=True)),
                ('required_file_format', models.CharField(choices=[('PDF', 'PDF'), ('NATIVE', 'Native / Editable File'), ('PDF_AND_NATIVE', 'PDF and Native File'), ('OTHER', 'Other')], default='PDF', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_vdrl_documents', to='core.documentmaster')),
                ('responsible_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_vdrl_documents', to='core.department')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_vdrl_documents', to=settings.AUTH_USER_MODEL)),
                ('source_template_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_sales_order_documents', to='core.customervdrltemplateitem')),
                ('vdrl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.salesordervdrl')),
            ],
            options={
                'ordering': ['vdrl', 'sequence_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='salesordervdrl',
            constraint=models.UniqueConstraint(fields=('sales_order', 'vdrl_number', 'revision'), name='unique_sales_order_vdrl_revision'),
        ),
        migrations.AddConstraint(
            model_name='salesordervdrldocument',
            constraint=models.UniqueConstraint(fields=('vdrl', 'sequence_number'), name='unique_sequence_per_sales_order_vdrl'),
        ),
        migrations.AddConstraint(
            model_name='salesordervdrldocument',
            constraint=models.UniqueConstraint(fields=('vdrl', 'source_template_item'), name='unique_template_item_per_sales_order_vdrl'),
        ),
    ]
