# Generated by Django 6.0.6 on 2026-07-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_salesorder_kickoff_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customervdrltemplateitem',
            name='customer_document_code',
        ),
    ]
