# Generated by Django 6.0.6 on 2026-07-14 18:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_customervdrltemplateitem_customer_document_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesordervdrldocument',
            name='current_action_since',
            field=models.DateTimeField(blank=True, help_text='Date and time when the current holder received the action.', null=True),
        ),
        migrations.AddField(
            model_name='salesordervdrldocument',
            name='current_cycle',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 before first submission, 1 for first submission cycle, etc.'),
        ),
        migrations.AddField(
            model_name='salesordervdrldocument',
            name='customer_review_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesordervdrldocument',
            name='final_approval_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesordervdrldocument',
            name='first_submission_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesordervdrldocument',
            name='last_customer_return_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesordervdrldocument',
            name='last_submission_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DocumentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('ASSIGNED_INTERNAL', 'Assigned to Internal Owner'), ('READY_INITIAL_SUBMISSION', 'Ready for Initial Submission'), ('INITIAL_SUBMISSION', 'Initial Submission to Customer'), ('RETURNED_WITH_COMMENTS', 'Returned by Customer with Comments'), ('COMMENT_ASSESSMENT', 'Comment Assessment Started'), ('REVISION_STARTED', 'Document Revision Started'), ('REVISION_COMPLETED', 'Document Revision Completed'), ('CRS_STARTED', 'CRS Preparation Started'), ('CRS_COMPLETED', 'CRS Preparation Completed'), ('RESUBMISSION', 'Resubmitted to Customer'), ('APPROVED_WITH_COMMENTS', 'Approved with Comments'), ('FINAL_APPROVAL', 'Final Approval - No Comments'), ('ON_HOLD', 'Placed On Hold'), ('REACTIVATED', 'Reactivated'), ('MARK_NOT_APPLICABLE', 'Marked Not Applicable'), ('CANCELLED', 'Cancelled')], max_length=40)),
                ('transaction_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Actual date and time when this transaction occurred.')),
                ('cycle_number', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('revision', models.CharField(blank=True, help_text='Document revision applicable to this transaction. Leave blank to retain the current revision.', max_length=20)),
                ('status_before', models.CharField(blank=True, choices=[('PLANNED', 'Planned'), ('UNDER_PREPARATION', 'Under Preparation'), ('INTERNAL_REVIEW', 'Internal Review'), ('READY_FOR_SUBMISSION', 'Ready for Submission'), ('SUBMITTED', 'Submitted to Customer'), ('UNDER_CUSTOMER_REVIEW', 'Under Customer Review'), ('RETURNED_WITH_COMMENTS', 'Returned with Comments'), ('COMMENT_ASSESSMENT', 'Comment Assessment in Progress'), ('REVISION_IN_PROGRESS', 'Revision in Progress'), ('CRS_IN_PROGRESS', 'CRS Preparation in Progress'), ('READY_FOR_RESUBMISSION', 'Ready for Resubmission'), ('RESUBMITTED', 'Resubmitted to Customer'), ('APPROVED_WITH_COMMENTS', 'Approved with Comments'), ('APPROVED', 'Approved'), ('ON_HOLD', 'On Hold'), ('NOT_APPLICABLE', 'Not Applicable'), ('CANCELLED', 'Cancelled')], default='', editable=False, max_length=40)),
                ('status_after', models.CharField(blank=True, choices=[('PLANNED', 'Planned'), ('UNDER_PREPARATION', 'Under Preparation'), ('INTERNAL_REVIEW', 'Internal Review'), ('READY_FOR_SUBMISSION', 'Ready for Submission'), ('SUBMITTED', 'Submitted to Customer'), ('UNDER_CUSTOMER_REVIEW', 'Under Customer Review'), ('RETURNED_WITH_COMMENTS', 'Returned with Comments'), ('COMMENT_ASSESSMENT', 'Comment Assessment in Progress'), ('REVISION_IN_PROGRESS', 'Revision in Progress'), ('CRS_IN_PROGRESS', 'CRS Preparation in Progress'), ('READY_FOR_RESUBMISSION', 'Ready for Resubmission'), ('RESUBMITTED', 'Resubmitted to Customer'), ('APPROVED_WITH_COMMENTS', 'Approved with Comments'), ('APPROVED', 'Approved'), ('ON_HOLD', 'On Hold'), ('NOT_APPLICABLE', 'Not Applicable'), ('CANCELLED', 'Cancelled')], default='', editable=False, max_length=40)),
                ('holder_after_event', models.CharField(blank=True, choices=[('INTERNAL', 'Internal'), ('CUSTOMER', 'Customer'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='', editable=False, max_length=20)),
                ('customer_comment_count', models.PositiveIntegerField(default=0)),
                ('crs_reference', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('elapsed_calendar_days', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calendar days elapsed since the previous transaction.', max_digits=10)),
                ('elapsed_holder_type', models.CharField(blank=True, choices=[('INTERNAL', 'Internal'), ('CUSTOMER', 'Customer'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='', editable=False, help_text='Holder responsible for the elapsed period before this event.', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vdrl_transactions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.salesordervdrldocument')),
                ('elapsed_responsible_person', models.ForeignKey(blank=True, editable=False, help_text='Internal person responsible for the elapsed period.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsible_person_after_event', models.ForeignKey(blank=True, help_text='Internal person responsible after this transaction. Leave blank when the document moves to the customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vdrl_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document', 'transaction_at', 'id'],
                'indexes': [models.Index(fields=['document', 'transaction_at'], name='core_docume_documen_b997a2_idx')],
            },
        ),
    ]
