# Generated by Django 6.0.6 on 2026-07-14 20:05

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_salesordervdrldocument_current_action_since_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(choices=[('WORKING', 'Internal Working File'), ('SUBMITTED', 'Submitted to Customer'), ('CUSTOMER_RETURNED', 'Customer Returned / Commented Copy'), ('CRS', 'Comments Resolution Sheet'), ('APPROVED', 'Approved Final File'), ('TRANSMITTAL', 'Submission Transmittal'), ('SUPPORTING', 'Supporting Document'), ('OTHER', 'Other')], max_length=30)),
                ('revision', models.CharField(blank=True, help_text='Document revision applicable to this file.', max_length=20)),
                ('cycle_number', models.PositiveSmallIntegerField(default=0, help_text='Submission cycle applicable to this file.')),
                ('file', models.FileField(upload_to=core.models.vdrl_document_upload_path)),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_current', models.BooleanField(default=True, help_text='Indicates the latest/current file for this file type.')),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.salesordervdrldocument')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_vdrl_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document', '-uploaded_at', '-id'],
                'indexes': [models.Index(fields=['document', 'file_type', 'is_current'], name='core_docume_documen_9124ef_idx')],
            },
        ),
    ]
