# Generated by Django 6.0.6 on 2026-07-15 16:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_documentfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRSRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_number', models.PositiveSmallIntegerField(default=1)),
                ('document_revision', models.CharField(blank=True, max_length=20)),
                ('crs_reference', models.CharField(blank=True, help_text='Example: CRS-001', max_length=100)),
                ('expected_comment_count', models.PositiveIntegerField(default=0, help_text='Number of comments received from the customer.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('INTERNAL_REVIEW', 'Internal Review'), ('READY_FOR_SUBMISSION', 'Ready for Submission'), ('SUBMITTED', 'Submitted to Customer'), ('CUSTOMER_REVIEW', 'Under Customer Review'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_crs_registers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crs_registers', to=settings.AUTH_USER_MODEL)),
                ('crs_file', models.ForeignKey(blank=True, help_text='Optional CRS file uploaded under the VDRL document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_crs_registers', to='core.documentfile')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crs_registers', to='core.salesordervdrldocument')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_crs_registers', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_crs_registers', to=settings.AUTH_USER_MODEL)),
                ('source_return_transaction', models.ForeignKey(blank=True, help_text='Customer-return transaction that initiated this CRS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crs_registers', to='core.documenttransaction')),
            ],
            options={
                'ordering': ['document', '-cycle_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRSComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_number', models.CharField(help_text='Example: 1, 2, 3A, C-01', max_length=50)),
                ('page_reference', models.CharField(blank=True, max_length=100)),
                ('clause_reference', models.CharField(blank=True, max_length=150)),
                ('customer_comment', models.TextField()),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical'), ('QUALITY', 'Quality'), ('CONTRACTUAL', 'Contractual'), ('COMMERCIAL', 'Commercial'), ('EDITORIAL', 'Editorial'), ('OTHER', 'Other')], default='TECHNICAL', max_length=20)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending Assessment'), ('ACCEPTED', 'Accepted'), ('PARTIALLY_ACCEPTED', 'Partially Accepted'), ('NOT_ACCEPTED', 'Not Accepted'), ('CLARIFICATION_REQUIRED', 'Clarification Required')], default='PENDING', max_length=30)),
                ('supplier_response', models.TextField(blank=True)),
                ('internal_action_required', models.TextField(blank=True, help_text='Describe the document change or internal action required.')),
                ('document_update_status', models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('PENDING', 'Update Pending'), ('UPDATED', 'Document Updated')], default='PENDING', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESPONSE_PREPARED', 'Response Prepared'), ('INTERNAL_REVIEW', 'Internal Review'), ('READY_FOR_SUBMISSION', 'Ready for Submission'), ('CUSTOMER_REVIEW', 'Under Customer Review'), ('CLOSED', 'Closed')], default='OPEN', max_length=30)),
                ('customer_disposition', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REPEATED', 'Comment Repeated'), ('REJECTED', 'Response Rejected')], default='PENDING', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_response_date', models.DateField(blank=True, null=True)),
                ('response_completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crs_comments', to='core.department')),
                ('assigned_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crs_comments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crs_comments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_crs_comments', to=settings.AUTH_USER_MODEL)),
                ('crs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.crsregister')),
            ],
            options={
                'ordering': ['crs', 'comment_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='crsregister',
            constraint=models.UniqueConstraint(fields=('document', 'cycle_number'), name='unique_crs_cycle_per_vdrl_document'),
        ),
        migrations.AddConstraint(
            model_name='crscomment',
            constraint=models.UniqueConstraint(fields=('crs', 'comment_number'), name='unique_comment_number_per_crs'),
        ),
    ]
