# Generated by Django 6.0.7 on 2026-07-15 17:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_crsregister_crscomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('notification_date', models.DateField(default=django.utils.timezone.localdate)),
                ('digest_key', models.CharField(default='DAILY_VDRL_DIGEST', max_length=50)),
                ('subject', models.CharField(max_length=250)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('delivery_status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vdrl_notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-notification_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('recipient_email', 'notification_date', 'digest_key'), name='unique_daily_vdrl_digest_per_recipient')],
            },
        ),
    ]
