# Generated by Django 6.0.7 on 2026-07-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notificationlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesordervdrldocument',
            options={'ordering': ['vdrl', 'sequence_number'], 'permissions': [('view_all_vdrl_data', 'Can view all VDRL data'), ('manage_vdrl_document_details', 'Can manage VDRL document details'), ('manage_vdrl_workflow', 'Can manage VDRL workflow'), ('manage_vdrl_files', 'Can manage VDRL document files'), ('manage_crs', 'Can manage CRS registers and comments'), ('view_management_reports', 'Can view VDRL management reports')]},
        ),
    ]
