# Generated by Django 6.0.7 on 2026-07-16 17:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_salesordervdrldocument_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesordervdrldocument',
            options={'ordering': ['vdrl', 'sequence_number'], 'permissions': [('view_all_vdrl_data', 'Can view all VDRL data'), ('manage_vdrl_document_details', 'Can manage VDRL document details'), ('manage_vdrl_workflow', 'Can manage VDRL workflow'), ('manage_vdrl_files', 'Can manage VDRL document files'), ('manage_crs', 'Can manage CRS registers and comments'), ('view_management_reports', 'Can view VDRL management reports'), ('bulk_import_vdrl_data', 'Can bulk import VDRL data'), ('view_audit_log', 'Can view VDRL audit log')]},
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('LOGIN', 'Logged In'), ('LOGOUT', 'Logged Out'), ('VIEW', 'Viewed'), ('DOWNLOAD', 'Downloaded'), ('EXPORT', 'Exported'), ('IMPORT', 'Imported'), ('WORKFLOW', 'Workflow Action'), ('SYSTEM', 'System Action')], max_length=20)),
                ('model_label', models.CharField(blank=True, db_index=True, help_text='Example: core.SalesOrderVDRLDocument', max_length=150)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Field-level old and new values.')),
                ('event_data', models.JSONField(blank=True, default=dict, help_text='Additional data related to the event.')),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vdrl_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('crs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.crsregister')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.salesordervdrldocument')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.salesorder')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('export_audit_log', 'Can export VDRL audit log')],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='audit_actor_date_idx'), models.Index(fields=['action', 'created_at'], name='audit_action_date_idx'), models.Index(fields=['model_label', 'object_id'], name='audit_object_idx')],
            },
        ),
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('WORKFLOW', 'Workflow'), ('CRS', 'CRS Comment'), ('DUE_DATE', 'Due Date'), ('APPROVAL', 'Approval'), ('FILE', 'Document File'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('title', models.CharField(max_length=250)),
                ('message', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, help_text='Used to prevent duplicate active notifications.', max_length=250)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_in_app_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_crs_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_app_notifications', to='core.crscomment')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_app_notifications', to='core.salesordervdrldocument')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notification_unread_idx')],
            },
        ),
    ]
