# Generated by Django 6.0.7 on 2026-07-20 14:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_salesordervdrldocument_options_auditlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customervdrltemplate',
            name='application_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_engineer_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='Application Engineer'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, help_text='Only these users may view this Sales Order and its related VDRL documents.', related_name='authorized_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='Users Allowed to Access This Sales Order'),
        ),
        migrations.CreateModel(
            name='DocumentOpenPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open — Awaiting Application Engineer'), ('RESPONDED', 'Responded — Awaiting Contributor Review'), ('MORE_INFORMATION_REQUIRED', 'More Information Required'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=40)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('is_blocking', models.BooleanField(default=True)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('latest_response_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_remark', models.TextField(blank=True)),
                ('response_cycle', models.PositiveIntegerField(default=0)),
                ('application_engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_engineer_open_points', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_document_open_points', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_document_open_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentOpenPointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('RAISED', 'Raised'), ('RESPONDED', 'Responded'), ('MORE_INFORMATION_REQUIRED', 'More Information Required'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('CONTRIBUTOR_REASSIGNED', 'Contributor Reassigned')], max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=40)),
                ('to_status', models.CharField(blank=True, max_length=40)),
                ('responsible_party', models.CharField(choices=[('CONTRIBUTOR', 'Contributor'), ('APPLICATION_ENGINEER', 'Application Engineer'), ('DEPARTMENT_MANAGER', 'Department Manager'), ('DOCUMENT_CONTROLLER', 'Document Controller'), ('SYSTEM', 'System')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='open_point_attachments/%Y/%m/')),
                ('elapsed_since_previous_seconds', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('open_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.documentopenpoint')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('WITH_DOCUMENT_CONTROLLER', 'With Document Controller'), ('WITH_DEPARTMENT_MANAGER', 'With Department Manager'), ('WITH_CONTRIBUTOR', 'With Contributor'), ('AWAITING_APPLICATION_ENGINEER', 'Awaiting Application Engineer'), ('CONTRIBUTOR_REVIEWING_RESPONSE', 'Contributor Reviewing AE Response'), ('SUBMITTED_FOR_DEPARTMENT_REVIEW', 'Submitted for Department Review'), ('RETURNED_FOR_REWORK', 'Returned for Rework'), ('READY_FOR_CUSTOMER_SUBMISSION', 'Ready for Customer Submission'), ('SUBMITTED_TO_CUSTOMER', 'Submitted to Customer'), ('CUSTOMER_RETURNED', 'Customer Returned'), ('CUSTOMER_APPROVED', 'Customer Approved'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], db_index=True, default='WITH_DOCUMENT_CONTROLLER', max_length=50)),
                ('resume_status', models.CharField(blank=True, choices=[('WITH_DOCUMENT_CONTROLLER', 'With Document Controller'), ('WITH_DEPARTMENT_MANAGER', 'With Department Manager'), ('WITH_CONTRIBUTOR', 'With Contributor'), ('AWAITING_APPLICATION_ENGINEER', 'Awaiting Application Engineer'), ('CONTRIBUTOR_REVIEWING_RESPONSE', 'Contributor Reviewing AE Response'), ('SUBMITTED_FOR_DEPARTMENT_REVIEW', 'Submitted for Department Review'), ('RETURNED_FOR_REWORK', 'Returned for Rework'), ('READY_FOR_CUSTOMER_SUBMISSION', 'Ready for Customer Submission'), ('SUBMITTED_TO_CUSTOMER', 'Submitted to Customer'), ('CUSTOMER_RETURNED', 'Customer Returned'), ('CUSTOMER_APPROVED', 'Customer Approved'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('planned_submission_date', models.DateField(blank=True, null=True)),
                ('department_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('contributor_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('last_reassigned_at', models.DateTimeField(blank=True, null=True)),
                ('current_action_since', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributor_document_workflows', to=settings.AUTH_USER_MODEL)),
                ('contributor_assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributor_assigned_workflows', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_workflows', to='core.department')),
                ('department_assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_assigned_workflows', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='core.salesordervdrldocument')),
            ],
            options={
                'ordering': ['planned_submission_date', 'document_id'],
                'permissions': [('assign_document_department', 'Can assign document department'), ('assign_document_contributor', 'Can assign document contributor'), ('reassign_document_contributor', 'Can reassign document contributor'), ('raise_document_open_point', 'Can raise document open point'), ('respond_document_open_point', 'Can respond to document open point'), ('close_document_open_point', 'Can close document open point'), ('review_department_document', 'Can review department document'), ('record_customer_document_action', 'Can record customer document action')],
            },
        ),
        migrations.AddField(
            model_name='documentopenpoint',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_points', to='core.documentworkflow'),
        ),
        migrations.CreateModel(
            name='DocumentAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DEPARTMENT_ASSIGNED', 'Department Assigned'), ('CONTRIBUTOR_ASSIGNED', 'Contributor Assigned'), ('CONTRIBUTOR_REASSIGNED', 'Contributor Reassigned')], max_length=40)),
                ('previous_planned_date', models.DateField(blank=True, null=True)),
                ('new_planned_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('new_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('new_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.department')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_assignment_actions', to=settings.AUTH_USER_MODEL)),
                ('previous_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('previous_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.department')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='core.documentworkflow')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentWorkflowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DEPARTMENT_ASSIGNED', 'Department Assigned'), ('CONTRIBUTOR_ASSIGNED', 'Contributor Assigned'), ('CONTRIBUTOR_REASSIGNED', 'Contributor Reassigned'), ('OPEN_POINT_RAISED', 'Open Point Raised'), ('OPEN_POINT_RESPONDED', 'Open Point Responded'), ('OPEN_POINT_CLOSED', 'Open Point Closed'), ('SUBMITTED_FOR_REVIEW', 'Submitted for Department Review'), ('RETURNED_FOR_REWORK', 'Returned for Rework'), ('INTERNALLY_APPROVED', 'Internally Approved'), ('CUSTOMER_SUBMITTED', 'Submitted to Customer'), ('CUSTOMER_RETURNED', 'Customer Returned'), ('CUSTOMER_APPROVED', 'Customer Approved')], max_length=50)),
                ('from_status', models.CharField(blank=True, max_length=50)),
                ('to_status', models.CharField(blank=True, max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('revision', models.CharField(blank=True, max_length=50)),
                ('elapsed_seconds', models.PositiveBigIntegerField(default=0, help_text='Time spent in the previous workflow status.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_workflow_transactions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.documentworkflow')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='documentopenpoint',
            index=models.Index(fields=['application_engineer', 'status'], name='openpoint_ae_status_idx'),
        ),
        migrations.AddIndex(
            model_name='documentopenpoint',
            index=models.Index(fields=['workflow', 'status'], name='openpoint_workflow_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentopenpoint',
            constraint=models.UniqueConstraint(fields=('workflow', 'reference_number'), name='unique_open_point_reference'),
        ),
    ]
