# Generated by Django 6.0.7 on 2026-07-21 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_salesorder_options_salesorder_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-order_date', 'sales_order_number'], 'permissions': [('submit_sales_order_for_approval', 'Can submit Sales Order for approval'), ('approve_sales_order_as_sales_manager', 'Can approve Sales Order as Sales Manager'), ('approve_sales_order_as_project_manager', 'Can approve Sales Order as Project Manager'), ('reject_sales_order', 'Can reject Sales Order'), ('assign_document_controller', 'Can assign Document Controller after approval'), ('view_sales_order_approval_history', 'Can view Sales Order approval history')]},
        ),
        migrations.AddField(
            model_name='salesorder',
            name='application_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_application_engineer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='backup_document_controllers',
            field=models.ManyToManyField(blank=True, related_name='backup_document_controlled_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='Backup Document Controllers'),
        ),
        migrations.AlterField(
            model_name='customervdrltemplate',
            name='application_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vdrl_template_application_engineer', to=settings.AUTH_USER_MODEL, verbose_name='Application Engineer'),
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_code', models.CharField(max_length=30, unique=True)),
                ('team_name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_project_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Team',
                'verbose_name_plural': 'Project Teams',
                'ordering': ['team_code'],
            },
        ),
        migrations.AddField(
            model_name='salesorder',
            name='project_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='core.projectteam'),
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('APPLICATION_ENGINEER', 'Application Engineer'), ('DOCUMENT_CONTROLLER', 'Document Controller')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('project_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.projectteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project_team', 'role', 'user__first_name', 'user__username'],
                'indexes': [models.Index(fields=['project_team', 'role', 'is_active'], name='project_team_role_idx')],
                'constraints': [models.UniqueConstraint(fields=('project_team', 'user', 'role'), name='unique_project_team_member_role')],
            },
        ),
    ]
