# Generated by Django 6.0.7 on 2026-07-26 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Disable all module access for this user without deleting the record.')),
                ('can_access_vdrl', models.BooleanField(default=False)),
                ('can_access_itp_noi', models.BooleanField(default=False)),
                ('can_access_calibration', models.BooleanField(default=False)),
                ('vdrl_all_sales_orders', models.BooleanField(default=False)),
                ('itp_all_sales_orders', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_module_access_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User module access',
                'verbose_name_plural': 'User module access',
                'ordering': ['user__username'],
            },
        ),
    ]
