# Generated by Django 6.0.7 on 2026-07-26 09:01

import django.core.validators
import django.db.models.deletion
import itp.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_salesorder_sales_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NOINumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('object_type', models.CharField(max_length=120)),
                ('object_id', models.CharField(max_length=120)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itp_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ITPAnnexure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(max_length=160)),
                ('revision', models.CharField(max_length=40)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('original_file', models.FileField(upload_to=itp.models.annexure_upload_path)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('EXTRACTING', 'Extraction in progress'), ('QC_REVIEW', 'QC review'), ('CORRECTION_REQUIRED', 'Correction required'), ('APPROVED', 'QC approved'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('FAILED', 'Import failed')], default='UPLOADED', max_length=30)),
                ('import_summary', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_itp_annexures', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itp_annexures', to='core.salesorder')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_itp_annexures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('activate_annexure', 'Can activate ITP annexure revision')],
            },
        ),
        migrations.CreateModel(
            name='ITPAnnexureLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('po_line_no', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('inspection_class', models.CharField(blank=True, max_length=80)),
                ('nde_applicable', models.CharField(blank=True, max_length=255)),
                ('temperature_text', models.CharField(blank=True, max_length=120)),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tag_number', models.CharField(blank=True, max_length=255)),
                ('piping_class', models.CharField(blank=True, max_length=255)),
                ('service', models.CharField(blank=True, max_length=120)),
                ('insulation', models.CharField(blank=True, max_length=120)),
                ('datasheet_number', models.CharField(blank=True, max_length=255)),
                ('valve_size', models.CharField(blank=True, max_length=80)),
                ('pressure_class', models.CharField(blank=True, max_length=80)),
                ('valve_type', models.CharField(blank=True, max_length=120)),
                ('body_material', models.CharField(blank=True, max_length=160)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('annexure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='itp.itpannexure')),
            ],
            options={
                'ordering': ['row_number', 'po_line_no'],
            },
        ),
        migrations.CreateModel(
            name='ITPClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_code', models.CharField(blank=True, max_length=20)),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('clause_number', models.CharField(max_length=60)),
                ('clause_code', models.CharField(max_length=100)),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('activity', models.TextField(blank=True)),
                ('reference_document', models.TextField(blank=True)),
                ('characteristics', models.TextField(blank=True)),
                ('inspection_extent', models.TextField(blank=True)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('verifying_document', models.TextField(blank=True)),
                ('is_hold_point', models.BooleanField(default=False)),
                ('hold_release_mode', models.CharField(choices=[('AUTO', 'Release automatically after completion'), ('MANUAL', 'Manual QC/customer release required')], default='AUTO', max_length=10)),
                ('completion_followup_days', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_source', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='itp.itpclause')),
            ],
            options={
                'ordering': ['sequence_order', 'clause_code'],
            },
        ),
        migrations.CreateModel(
            name='ITPClauseDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('FS', 'Finish to start'), ('RBS', 'Review before start')], default='FS', max_length=10)),
                ('mandatory', models.BooleanField(default=True)),
                ('applies_to_same_annexure_line', models.BooleanField(default=True)),
                ('blocking_if_predecessor_is_hold', models.BooleanField(default=True)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_links', to='itp.itpclause')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_links', to='itp.itpclause')),
            ],
        ),
        migrations.CreateModel(
            name='ITPDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(max_length=160)),
                ('revision', models.CharField(max_length=40)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('source_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel')], max_length=10)),
                ('original_file', models.FileField(upload_to=itp.models.itp_upload_path)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('EXTRACTING', 'Extraction in progress'), ('QC_REVIEW', 'QC review'), ('CORRECTION_REQUIRED', 'Correction required'), ('APPROVED', 'QC approved'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('FAILED', 'Import failed')], default='UPLOADED', max_length=30)),
                ('extraction_summary', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_itps', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itp_documents', to='core.salesorder')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_itps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('activate_itp', 'Can activate ITP revision')],
            },
        ),
        migrations.AddField(
            model_name='itpclause',
            name='itp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='itp.itpdocument'),
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('ERROR', 'Error')], default='WARNING', max_length=20)),
                ('source_location', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annexure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_issues', to='itp.itpannexure')),
                ('itp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_issues', to='itp.itpdocument')),
            ],
            options={
                'ordering': ['is_resolved', 'severity', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ITPLineClauseMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_applicable', models.BooleanField(default=True)),
                ('required_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('extent_override', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('AUTO', 'Auto suggested'), ('IMPORTED', 'Imported'), ('MANUAL', 'Manual')], default='AUTO', max_length=20)),
                ('review_status', models.CharField(choices=[('SUGGESTED', 'Suggested - review required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected / not applicable')], default='SUGGESTED', max_length=20)),
                ('rationale', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('annexure_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clause_mappings', to='itp.itpannexureline')),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_mappings', to='itp.itpclause')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_itp_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['clause__sequence_order', 'annexure_line__row_number'],
            },
        ),
        migrations.CreateModel(
            name='ITPStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('itp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='itp.itpdocument')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ITPClauseIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_code', models.CharField(blank=True, max_length=30)),
                ('sampling_text', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='itp.itpclause')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='itp.itpstakeholder')),
            ],
        ),
        migrations.CreateModel(
            name='NOICoverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offered_quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('completed_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('heat_numbers', models.TextField(blank=True)),
                ('serial_numbers', models.TextField(blank=True)),
                ('previous_activity_state', models.JSONField(blank=True, default=list)),
                ('blocked_on_creation', models.BooleanField(default=False)),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAIVED', 'Waived'), ('NOT_COMPLETED', 'Not completed')], default='PENDING', max_length=30)),
                ('actual_completion_at', models.DateTimeField(blank=True, null=True)),
                ('report_reference', models.CharField(blank=True, max_length=255)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to=itp.models.evidence_upload_path)),
                ('annexure_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noi_coverages', to='itp.itpannexureline')),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noi_coverages', to='itp.itpclause')),
            ],
            options={
                'ordering': ['clause__sequence_order', 'annexure_line__row_number'],
            },
        ),
        migrations.CreateModel(
            name='ITPActivityExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('NOI', 'NOI'), ('INTERNAL', 'Internal completion')], default='INTERNAL', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('NOT_COMPLETED', 'Not completed'), ('RELEASED', 'Hold point released'), ('WAIVED', 'Waived'), ('REJECTED', 'Rejected'), ('OVERRIDDEN', 'Authorised override')], default='PLANNED', max_length=30)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reference', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to=itp.models.evidence_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_itp_activities', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_itp_hold_points', to=settings.AUTH_USER_MODEL)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='itp.itplineclausemapping')),
                ('noi_coverage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='itp.noicoverage')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('release_hold_point', 'Can release ITP hold point'), ('override_hold_point', 'Can override incomplete hold point')],
            },
        ),
        migrations.CreateModel(
            name='NoticeOfInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('WAIVED', 'Waived'), ('RESCHEDULED', 'Rescheduled'), ('ATTENDED', 'Attended'), ('COMPLETED', 'Completed'), ('NOT_COMPLETED', 'Not completed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('completion_status', models.CharField(choices=[('PENDING', 'Pending confirmation'), ('COMPLETED', 'Completed'), ('NOT_COMPLETED', 'Not completed')], default='PENDING', max_length=30)),
                ('completion_confirmation_due_at', models.DateTimeField(blank=True, null=True)),
                ('completion_prompt_sent_at', models.DateTimeField(blank=True, null=True)),
                ('completion_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annexure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_notices', to='itp.itpannexure')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_nois', to=settings.AUTH_USER_MODEL)),
                ('itp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_notices', to='itp.itpdocument')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_nois', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_start', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='noicoverage',
            name='noi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='itp.noticeofinspection'),
        ),
        migrations.CreateModel(
            name='NOICompletionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='OPEN', max_length=20)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noi_completion_tasks', to=settings.AUTH_USER_MODEL)),
                ('noi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_task', to='itp.noticeofinspection')),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('COMPLETION_DUE', 'Completion confirmation due'), ('COMPLETION_OVERDUE', 'Completion confirmation overdue'), ('HOLD_INCOMPLETE', 'Previous Hold Point incomplete'), ('HOLD_AWAITING_RELEASE', 'Hold Point awaiting release'), ('IMPORT_ERROR', 'Import error')], max_length=40)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itp_workflow_alerts', to=settings.AUTH_USER_MODEL)),
                ('coverage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='itp.noicoverage')),
                ('noi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='itp.noticeofinspection')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_itp_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_resolved', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='itpannexure',
            constraint=models.UniqueConstraint(fields=('sales_order', 'document_number', 'revision'), name='unique_annexure_revision_per_sales_order'),
        ),
        migrations.AddConstraint(
            model_name='itpannexureline',
            constraint=models.UniqueConstraint(fields=('annexure', 'po_line_no'), name='unique_po_line_per_annexure'),
        ),
        migrations.AddConstraint(
            model_name='itpclausedependency',
            constraint=models.UniqueConstraint(fields=('predecessor', 'successor'), name='unique_clause_dependency'),
        ),
        migrations.AddConstraint(
            model_name='itpdocument',
            constraint=models.UniqueConstraint(fields=('sales_order', 'document_number', 'revision'), name='unique_itp_revision_per_sales_order'),
        ),
        migrations.AddConstraint(
            model_name='itpclause',
            constraint=models.UniqueConstraint(fields=('itp', 'clause_code'), name='unique_clause_code_per_itp'),
        ),
        migrations.AddConstraint(
            model_name='itplineclausemapping',
            constraint=models.UniqueConstraint(fields=('clause', 'annexure_line'), name='unique_clause_annexure_line_mapping'),
        ),
        migrations.AddConstraint(
            model_name='itpstakeholder',
            constraint=models.UniqueConstraint(fields=('itp', 'name'), name='unique_itp_stakeholder'),
        ),
        migrations.AddConstraint(
            model_name='itpclauseintervention',
            constraint=models.UniqueConstraint(fields=('clause', 'stakeholder'), name='unique_clause_stakeholder_intervention'),
        ),
        migrations.AddConstraint(
            model_name='noicoverage',
            constraint=models.UniqueConstraint(fields=('noi', 'clause', 'annexure_line'), name='unique_noi_clause_line_coverage'),
        ),
    ]
