# Generated by Django 6.0.7 on 2026-07-26 12:26

import calibration.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_salesorder_sales_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationLaboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('accreditation_number', models.CharField(blank=True, max_length=120)),
                ('accreditation_expiry', models.DateField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Instrument categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_number', models.CharField(help_text='Internal instrument / gauge identification number.', max_length=80, unique=True)),
                ('purchase_serial_number', models.CharField(blank=True, max_length=120)),
                ('manufacturer_serial_number', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=160)),
                ('model_number', models.CharField(blank=True, max_length=120)),
                ('measurement_range', models.CharField(blank=True, max_length=160)),
                ('least_count', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('calibration_frequency_days', models.PositiveIntegerField(default=365, validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.CharField(blank=True, max_length=160)),
                ('latest_calibration_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_USE', 'In use'), ('DUE_SOON', 'Calibration due soon'), ('OVERDUE', 'Calibration overdue'), ('COLLECTED', 'Collected from user'), ('SENT_TO_LAB', 'Sent to laboratory'), ('RETURNED', 'Returned from laboratory'), ('QUARANTINED', 'Quarantined'), ('UNDER_REPAIR', 'Under repair'), ('NOT_USABLE', 'Not usable'), ('RETIRED', 'Retired')], default='IN_USE', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calibration_instruments', to=settings.AUTH_USER_MODEL)),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodied_instruments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_instruments', to='core.department')),
                ('monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_instruments', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='calibration.instrumentcategory')),
            ],
            options={
                'ordering': ['asset_number'],
                'permissions': [('print_calibration_master_list', 'Can print calibration master list')],
            },
        ),
        migrations.CreateModel(
            name='CalibrationCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_number', models.PositiveIntegerField(editable=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COLLECTED', 'Collected from user'), ('SENT_TO_LAB', 'Sent to laboratory'), ('RETURNED', 'Returned from laboratory'), ('VERIFIED', 'QC verified'), ('RELEASED', 'Returned to production'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('collected_from_user_date', models.DateField(blank=True, null=True)),
                ('sent_to_lab_date', models.DateField(blank=True, null=True)),
                ('returned_from_lab_date', models.DateField(blank=True, null=True)),
                ('calibration_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=160)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=calibration.models.certificate_upload_path)),
                ('result', models.CharField(blank=True, choices=[('REUSABLE', 'Reusable'), ('REPAIRED', 'Repaired and reusable'), ('NOT_USABLE', 'Not usable')], max_length=30)),
                ('repair_details', models.TextField(blank=True)),
                ('qc_comments', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('returned_to_production_date', models.DateField(blank=True, null=True)),
                ('put_back_in_service_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calibration_cycles', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_calibration_cycles', to=settings.AUTH_USER_MODEL)),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calibration_cycles', to='calibration.calibrationlaboratory')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_cycles', to='calibration.instrument')),
            ],
            options={
                'ordering': ['-cycle_number'],
                'permissions': [('verify_calibration_cycle', 'Can verify calibration cycle'), ('release_calibrated_instrument', 'Can release calibrated instrument')],
            },
        ),
        migrations.CreateModel(
            name='CalibrationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('DUE_SOON', 'Due within 15 days'), ('OVERDUE', 'Overdue'), ('CERTIFICATE_PENDING', 'Certificate pending'), ('VERIFICATION_PENDING', 'QC verification pending')], max_length=40)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_alerts', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='calibration.instrument')),
            ],
            options={
                'ordering': ['is_resolved', 'due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('event_date', models.DateField(default=django.utils.timezone.localdate)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calibration_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_events', to='calibration.calibrationcycle')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='calibration.instrument')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_history_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='calibrationcycle',
            constraint=models.UniqueConstraint(fields=('instrument', 'cycle_number'), name='unique_calibration_cycle_number'),
        ),
        migrations.AddConstraint(
            model_name='calibrationalert',
            constraint=models.UniqueConstraint(condition=models.Q(('is_resolved', False)), fields=('instrument', 'alert_type'), name='unique_open_calibration_alert_type'),
        ),
    ]
